WaterCompanyWeb/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System;
using System.Linq;
using System.Threading.Tasks;
using WaterCompanyWeb.Data;
using WaterCompanyWeb.Data.Entities;
using WaterCompanyWeb.Helpers;
using WaterCompanyWeb.Models;
using Microsoft.AspNetCore.Authorization;

namespace WaterCompanyWeb.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientRepository _clientRepository;
        private readonly IUserHelper _userHelper;
        private readonly IImageHelper _imageHelper;
        private readonly IConverterHelper _converterHelper;

        public ClientsController(IClientRepository clientRepository,
            IUserHelper userHelper,
            IImageHelper imageHelper,
            IConverterHelper converterHelper
            )
        {
            _clientRepository = clientRepository;
            _userHelper = userHelper;
            _imageHelper = imageHelper;
            _converterHelper = converterHelper;
        }

        // GET: Clients
        [RoleAuthorization("Admin")]
        public async Task<IActionResult> Index()
        {
            return View(_clientRepository.GetAllWithUsers());
        }

        // GET: Clients/Details/5
        [RoleAuthorization("Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            var client = await _clientRepository.GetByIdAsync(id.Value);
            if (client == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        [RoleAuthorization("Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            var client = await _clientRepository.GetByIdAsync(id.Value);
            if (client == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }
            var model = _converterHelper.ToClientViewModel(client);
            return View(model);

        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RoleAuthorization("Admin")]
        public async Task<IActionResult> Edit(ClientViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var path = model.ImageUrl;

                    if (model.ImageFile != null && model.ImageFile.Length > 0)
                    {
                        path = await _imageHelper.UploadImageAsync(model.ImageFile, "clients");
                    }

                    var client = _converterHelper.ToClient(model, path, false);

                    client.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                    await _clientRepository.UpdateAsync(client);


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _clientRepository.ExistAsync(model.Id))
                    {
                        new NotFoundViewResult("ClientNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Clients/Delete/5
        [RoleAuthorization("Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            var client = await _clientRepository.GetByIdAsync(id.Value);
            if (client == null)
            {
                return new NotFoundViewResult("ClientNotFound");
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [RoleAuthorization("Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _clientRepository.GetByIdAsync(id);
            await _clientRepository.DeleteAsync(client);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ClientNotFound()
        {
            return View();
        }
    }
}

WaterCompanyWeb/Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WaterCompanyWeb.Data;
using WaterCompanyWeb.Data.Entities;
using WaterCompanyWeb.Helpers;

namespace WaterCompanyWeb.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly IInvoiceRepository _invoiceRepository;
        private readonly IWaterMeterRepository _waterMeterRepository;
        private readonly IClientRepository _clientRepository;
        private readonly IUserHelper _userHelper;
        private readonly IMailHelper _mailHelper;

        public InvoicesController(IInvoiceRepository invoiceRepository,
            IWaterMeterRepository waterMeterRepository,
            IClientRepository clientRepository,
            IUserHelper userHelper,
            IMailHelper mailHelper)
        {
            _invoiceRepository = invoiceRepository;
            _waterMeterRepository = waterMeterRepository;
            _clientRepository = clientRepository;
            _userHelper = userHelper;
            _mailHelper = mailHelper;
        }

        [RoleAuthorization("Staff")]
        // GET: Invoices
        public IActionResult Index()
        {
            var invoices = _invoiceRepository.GetAllInvoices();
            return View(invoices);
        }

        [RoleAuthorization("Staff")]
        // GET: Invoices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var invoices = await _invoiceRepository.GetByIdAsync(id.Value);
            if (invoices == null)
            {
                return NotFound();
            }
            var model = new Invoice();
            model.Date = invoices.Date;
            model.Client = invoices.Client;
            model.User = invoices.User;
            model.Value = invoices.Value;
            return View(model);

        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [RoleAuthorization("Staff")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Invoice model)
        {
            if (ModelState.IsValid)
            {
                var invoices = await _invoiceRepository.GetByIdAsync(id.Value);
                if (invoices != null)
                {
                    invoices.Date = model.Date;
                    invoices.User = model.User;
                    invoices.Client = model.Client;
                    invoices.WaterMeter = model.WaterMeter;
                    invoices.Value = invoices.Value;


                    await _invoiceRepository.UpdateAsync(invoices);
                    return View(model);
                }
            }
            return View(model);
        }

        // GET: Invoices/Delete/5
        [RoleAuthorization("Staff")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("InvoiceNotFound");
            }

            var invoice = await _invoiceRepository.GetByIdAsync(id.Value);
            if (invoice == null)
            {
                return new NotFoundViewResult("InvoiceNotFound");
            }
            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [RoleAuthorization("Staff")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var invoice = await _invoiceRepository.GetByIdAsync(id);
            await _invoiceRepository.DeleteAsync(invoice);
            return RedirectToAction(nameof(Index));
        }

        [RoleAuthorization("Client")]
        public async Task<IActionResult> InvoicesByClient()
        {
            Client client = await _clientRepository.GetClientByEmailAsync(this.User.Identity.Name);
            if (client == null)
            {
                return RedirectToAction("ClientNotFound", "Clients");
            }
            var invoices = _invoiceRepository.GetAllByClient(client.Email);
            if (invoices == null)
            {
                return new NotFoundViewResult("InvoiceNotFound");
            }
            return View(invoices);
        }

        public IActionResult InvoiceNotFound()
        {
            return View();
        }
    }
}

WaterCompanyWeb/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WaterCompanyWeb.Data;
using WaterCompanyWeb.Data.Entities;
using WaterCompanyWeb.Helpers;
using WaterCompanyWeb.Models;
using static System.Net.Mime.MediaTypeNames;

namespace WaterCompanyWeb.Controllers
{
    public class StaffsController : Controller
    {
        private readonly IStaffRepository _staffRepository;
        private readonly IUserHelper _userHelper;
        private readonly IImageHelper _imageHelper;
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;
        private readonly UserManager<User> _userManager;

        public StaffsController(IStaffRepository staffRepository,
            IUserHelper userHelper,
            IImageHelper imageHelper,
            DataContext context,
            IConverterHelper converterHelper,
            UserManager<User> userManager)
        {
            _staffRepository = staffRepository;
            _userHelper = userHelper;
            _imageHelper = imageHelper;
            _context = context;
            _converterHelper = converterHelper;
            _userManager = userManager;
        }

        // GET: Staffs
        public async Task<IActionResult> Index()
        {
            return View(_staffRepository.GetAllWithUsers());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("StaffNotFound");
            }

            var staff = await _staffRepository.GetByIdAsync(id.Value);
            if (staff == null)
            {
                return new NotFoundViewResult("StaffNotFound");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("StaffNotFound");
            }

            var staff = await _staffRepository.GetByIdAsync(id.Value);
            if (staff == null)
            {
                return new NotFoundViewResult("StaffNotFound");
            }
            var model = _converterHelper.ToStaffViewModel(staff);
            return View(model);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(StaffViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var path = model.ImageUrl;

                    if (model.ImageFile != null && model.ImageFile.Length > 0)
                    {
                        path = await _imageHelper.UploadImageAsync(model.ImageFile, "staffs");
                    }

                    var staff = _converterHelper.ToStaff(model, path, false);

                    staff.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                    await _staffRepository.UpdateAsync(staff);


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _staffRepository.ExistAsync(model.Id))
                    {
                        new NotFoundViewResult("StaffNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Staffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("StaffNotFound");
            }

            var staff = await _staffRepository.GetByIdAsync(id.Value);
            if (staff == null)
            {
                return new NotFoundViewResult("StaffNotFound");
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _staffRepository.GetByIdAsync(id);
            await _staffRepository.DeleteAsync(staff);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult StaffNotFound()
        {
            return View();
        }

        
    }
}

WaterCompanyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Water Company</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@600;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Water Company</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Client"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="WaterMeters" asp-action="WaterMetersByClient">Water Meters</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Invoices" asp-action="InvoicesByClient">Invoices</a>
                            </li>
                        }
                        else if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Staff"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="WaterMeters" asp-action="Index">Water Meters</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a>
                            </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="NotAuthorized">Water Meters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="NotAuthorized">Invoices</a>
                        </li>
                        }
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown nav-user">
                                <a class="dropdown-toggle nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Managment</a>
                                <ul class="dropdown-menu dropdown-menu-right nav-user-dropdown">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                                    </li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Staffs" asp-action="Index">Staffs</a> </li>
                                </ul>
                            </li>
                        }
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                            <a class="btn" asp-area="" asp-controller="Account" asp-action="ChangeUser"> @this.User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                            <a class="btn" asp-area="" asp-controller="Account" asp-action="Logout"> Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn" asp-area="" asp-controller="Account" asp-action="Login"><i class="fa-solid fa-user fa-lg"></i> Account</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            CINEL CET76 Júlio Caseiro | UFCD 5417 - Programação para a WEB-servidor (server-side) | 
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>